# This file is automatically generated by pyo3_stub_gen
# ruff: noqa: E501, F401

import typing

class Buffer:
    def __new__(cls, py_data: typing.Any, shape: typing.Sequence[int], strides: typing.Sequence[int], format: str) -> "Buffer": ...
    def __repr__(self) -> str: ...